server:
  port: 3344
spring:
  application:
    name: cloud-config-center  # 注册进eureka Server 的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Pathwax/springcloud-config.git # github 仓库位置
          ## 搜索目录
          search-paths:
            - springcloud-config
          # 读取的分支
          label: master
    bus:
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9092   #配置 kafka 服务器的地址和端口
    consumer:
      group-id: SpringCloudBus
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
# 暴露监控端点
management:
  endpoints: # 暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'